### PR TITLE
Misc cleaning

### PR DESCRIPTION
**Pull request by alexAubin**
- Remove use of `sudo` in scripts, not needed anymore (didn't touch the files in `conf/` though, some of these might still be ran as admin ?)
- Delete `scripts/prerequisites`, old stuff not relevant anymore
- Use `ynh_secure_remove` instead of `rm -rf`
- Misc improvements for the README ?
- Simplify a few things in install script

Not tested though :sweat_smile:

### CODE REVIEW

**Comment by pitchum** [comment]
I will test your PR on an Internet Cube this week.
Don't hesitate to ping me back I you haven't heard from me by Sunday.

**Comment by alexAubin** [comment]
Tested on CI : https://ci-apps-dev.yunohost.org/jenkins/view/aleks/job/vpnclient_ynh%20(aleks)/lastBuild/consoleFull

**Comment by pitchum** [comment]
Looks good to me.
I've tested on an internet cube :
- [X] fresh install
- [X] remove
- [X] upgrade from previous stable version
- [X] ynh-vpnclient-loadcubefile.sh

Ready to merge. I'll do that before the week-end if nobody complains until then.

**Comment by pitchum** [comment]
Actually the PR cannot be merged right now. I've missed an error: system user *vpnclient* is still present after uninstalling the app.

```
yunohost app remove vpnclient
...
Attention : userdel: user vpnclient is currently used by process 5760
Succès ! vpnclient a été supprimé
```
The process 5760 mentioned here is *php5-fpm.service* that is still running the config file */etc/php5/fpm/pool.d/vpnclient.conf* despite the following lines in the remove script:

    sudo rm -f /etc/php5/fpm/pool.d/${app}.conf
    sudo systemctl restart php5-fpm

I suspect this has something to do with a hack in yunohost 3 that silently translates on-the-fly all commands involving php5-fpm to their equivalent with php7.0-fpm.
I'll investigate this.

**Comment by alexAubin** [comment]
Uh yeah I spotted that too but I tought I fixed it ? At some point I placed the user deletion before the service restart (php), which I thought was slightly more elegant, but then spotted this so I reverted that changed in the last commits.

Did you get this even with the latest commits ?

**Comment by pitchum** [comment]
My bad. I messed up with my local repo. It was still pointing at origin/master (instead of origin/cleaning) after the test of upgrading...
Sorry for the noise. Merging this PR right now!

**Pull request merged**
