### PR TITLE
Brutal refactoring for more logging and readability of the script because debugging is hell

### PR DESCRIPTION
**Pull request by alexAubin**
So tonight I went full berserk after trying to help someone and realizing debugging is hell because there are very few messages indicating what is done and what isn't ... 

E.g. I ended up spending 30 minutes trying to see if ntp was the issue but it clearly wasnt. Just having a log message saying what's happening would help ... 

Since I was in berserk mode, I also ended up moving functions to group them by categories (e.g. firewall, dns) instead of this whole "setters" and "unsetters" mess when you have to jump 300 lines to see the "stop_firewall" associated to the "start" one...

So the commit is heavily unreadable but meh. Also untested .. gonna try that on my side some day...

### CODE REVIEW

**Comment by alexAubin** [comment]
Ran some tests on my machine and working, I was able to successfully start a VPN (and of course did test some errors in the process)

With this PR, one can `tail -f /var/log/ynh-vpnclient.log` to watch the vpn start and easily debug. If openvpn fails to start (which happens in many cases ?) the tail of the `openvpn-client.log` file will be displayed in `ynh-vpnclient.log` which makes it easier to debug as well ...

**Comment by alexAubin** [comment]
Bump in case anyone has time to give feedback to this PR :S

**Comment by alexAubin** [comment]
Alrighty folks, proposing to yolomerge in the coming days ...

**Comment by kay0u** [comment]
I'm ok with it, you can click THE button!

**Pull request merged**
