### PR TITLE
Change password field to type 'password'

### PR DESCRIPTION
**Pull request by realitygaps**
Otherwise an the password is clearly visible every time you access the settings page.

### CODE REVIEW

**Comment by jvaubourg** [comment]
I am agree with this PR, but just changing the input type is not enough. This requires to add a "repeat password" input, and a new test when the form is validated.

**Comment by realitygaps** [comment]
makes sense, but I guess i will use my fork for now as I dont want anyone to see my vpn password as i type it (which happened yesterday).

**Comment by jvaubourg** [comment]
I understand :). You can also take the time for adding the "repeat password" field, if you want ;). Otherwise, I'll take the time later, for doing it. Thank you.

**Comment by realitygaps** [comment]
I will try, but im not such a frontend person :)

**Comment by realitygaps** [comment]
On second thoughts, I dont understand why this field needs a repeat password. Its not setting a password, is that really necessary? I understand the need on forms that set passwords but this is just entering a connection password so I dont think it should be required to be repeated.

**Pull request merged**
