### PR TITLE
CSRF protection

### PR DESCRIPTION
**Pull request by randomstuff**

### CODE REVIEW

**Comment by pitchum** [comment]
I was not aware that we could protect from CSRF attacks by simply adding [custom request header](https://www.owasp.org/index.php/Cross-Site_Request_Forgery_(CSRF)_Prevention_Cheat_Sheet#Use_of_Custom_Request_Headers ). It seems that it only applies to Ajax requests but that's cool and simple though.

Your PR seems fine but please replace the use of 'fetch' with jQuery stuff and fix the typo (see above).
Then I'll have to test it before merging.

**Comment by randomstuff** [comment]
This approach is supposed to be not as good as using a CSRF token but this allows us to fix it ASAP. A patch with CSRF token (or something else) might come later on.

**Comment by randomstuff** [comment]
I have to say I'm not super familiar with jQuery :) but I'll have a look at that.

**Comment by randomstuff** [comment]
especially whether we can submit `<input type="file">`-like data with jQuery.

**Comment by randomstuff** [comment]
By the way, why don't you want to use fetch?

**Comment by randomstuff** [comment]
Fixed typo and used jQuery.

**Comment by randomstuff** [comment]
OK, the latest version is broken because jQuery is using XMLHttpRequest which follow redirect (in contrast to fetch).

**Comment by randomstuff** [comment]
OK, the `Location` header thing does not actually work because redirects are not exposed to XMLHttpRequest and fetch

**Comment by randomstuff** [comment]
Ugly hack to update the HTML and rerun the inititalization code. This ends up being not so great.

**Comment by randomstuff** [comment]
I think you somehow review the previous version. I already made these changes :)

**Comment by randomstuff** [comment]
Note that the current proposed change uses `FormData`. [Support for it is better](https://caniuse.com/#search=formdata) than for fetch.

**Pull request merged**
